---
title: "Other Majors"
author: "Vanessa Gonzalez"
date: "`r format(Sys.Date())`"
output: html_notebook
---

CS Grad: 
Yes - CS Students
OtherMajor - Left CS -OM
NG - Not Graduated

Data from 2008-2018 and excludes current students and students that graduated from CS.

Import Data Set
```{r}
library(readxl)
CourseDateData <- read_excel("CourseDateData.xlsx")

library(readxl)
CourseDateDataNoCS <- read_excel("CourseDateDataNoCS.xlsx")
```

```{r}
summary(CourseDateDataNoCS)
```

```{r}
str(CourseDateDataNoCS)
```

```{r}
DataNoCS <- CourseDateDataNoCS[-(1:6)]
str(DataNoCS)
```

```{r}
DataNoCS$GraduationStatus <- as.factor(DataNoCS$GraduationStatus)
DataNoCS$CsGrad <- as.factor(DataNoCS$CsGrad)
str(DataNoCS)
```


```{r}
dfCourseDatesNoCS <- as.data.frame(DataNoCS)
```

```{r}
JustOM<-subset(dfCourseDatesNoCS, CsGrad == 'OtherMajor')
head(JustOM)
```

```{r}
JustOM <- JustOM[-(1:2)]
JustOM <- JustOM[-(6)]
JustOM <- JustOM[-(9)]
JustOM <- JustOM[-(10)]
JustOM <- JustOM[-(11:13)]
str(JustOM)

```

Replace NA with 0
```{r}
JustOM[is.na(JustOM)] <- 0
head(JustOM)
```

```{r}
LastClassOM <- colnames(JustOM)[max.col(JustOM,ties.method="first")]
JustOM$LastClassOM <- LastClassOM
head(JustOM)
```

```{r}
summary(JustOM)
```

```{r}
library(caret)
library(lattice)
library(ggplot2)
```


```{r}
tbLastClassOM <- table(JustOM$LastClassOM)
tbLastClassOM
```

```{r}
dfLastClassOM <- as.data.frame(tbLastClassOM)
dfLastClassOM
```

```{r}
p<-ggplot(data=dfLastClassOM, aes(x= reorder(Var1, Freq),  y=Freq)) +
  geom_bar(stat="identity", fill="navyblue") +
  labs(title ="Last Highest CS Course Taken by Other Major Students", x = "Course", y = "Frequency") +
  ylim(0,45) +
  theme(axis.text.x=element_text(angle=90, hjust=1)) +
  geom_text(aes(label = Freq), hjust=-.5 , position = position_dodge(width = 1),inherit.aes = TRUE) +
  coord_flip()
p
```



